[versions]
hoplite = "2.8.0"
mordant = "3.0.0"

[libraries]
hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hoplite-yaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hoplite" }
hoplite-json = { module = "com.sksamuel.hoplite:hoplite-json", version.ref = "hoplite" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant"}

[bundles]
hoplite = [ "hoplite-core", "hoplite-json", "hoplite-yaml" ]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.20" }
